### ISSUE TITLE
[nextercism] any with folders: “open .../<folder>/<file>: not a directory” during download

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#9] opened 2017-08-18 19:53 UTC
@NobbZ commented on [Fri Aug 18 2017](https://github.com/exercism/cli/issues/465)

I tried to download erlangs hello world, but no success, it fails with an error:

```plain
$ nextercism download hello-world --track=erlang
2017/08/18 19:41:50 open /home/nobbz/nextercism/erlang/hello-world/include/exercism.hrl: not a directory
```

As it seems there is no equivalent of the debug subcommand, nor is there a `--verbose` option for download. So I am not able to provide more details.

---

@NobbZ commented on [Fri Aug 18 2017](https://github.com/exercism/cli/issues/465#issuecomment-323429020)

Oh, I took a closer look into what already got downloaded:

```
$ % ll $(nextercism w)/erlang/hello-world
total 16K
drwxr-xr-x 2 nobbz nobbz 4.0K Aug 18 19:39 .
drwxr-xr-x 3 nobbz nobbz 4.0K Aug 18 19:39 ..
-rw-r--r-- 1 nobbz nobbz  205 Aug 18 19:41 .solution.json
-rw-r--r-- 1 nobbz nobbz 2.1K Aug 18 19:41 README.md
-rw-r--r-- 1 nobbz nobbz    0 Aug 18 19:41 include
```

As you can see `include` is a plain and empty file whereas it should be a directory, which then shall contain `exercism.hrl`.

Probably simiral problems will occur on other tracks that use directories to structure the exercise. In the case of Erlang, Java, and Rust those structures are enforced/needed by the build tools used.

---

@NobbZ commented on [Fri Aug 18 2017](https://github.com/exercism/cli/issues/465#issuecomment-323431396)

Tested with Java, similar problem:

```plain
$ nextercism d hello-world --track java
2017/08/18 20:41:42 open /home/nobbz/nextercism/java/hello-world/src/main: not a directory

$ ll $(nextercism w)/java/hello-world/
total 36K
drwxr-xr-x 2 nobbz nobbz 4.0K Aug 18 20:41 .
drwxr-xr-x 3 nobbz nobbz 4.0K Aug 18 20:41 ..
-rw-r--r-- 1 nobbz nobbz  203 Aug 18 20:41 .solution.json
-rw-r--r-- 1 nobbz nobbz  161 Aug 18 20:41 HINTS.md
-rw-r--r-- 1 nobbz nobbz 1.2K Aug 18 20:41 README.md
-rw-r--r-- 1 nobbz nobbz 8.8K Aug 18 20:41 TUTORIAL.md
-rw-r--r-- 1 nobbz nobbz  256 Aug 18 20:41 build.gradle
-rw-r--r-- 1 nobbz nobbz    0 Aug 18 20:41 src
```

Similar symptom with `src`-folder.

---

@kytrinyx commented on [Fri Aug 18 2017](https://github.com/exercism/cli/issues/465#issuecomment-323444810)

@NobbZ Would you post this in the v2-feedback repo? We will need to track down whether it's in the API or the CLI.

**Comment by kytrinyx** [comment] 2017-08-19 01:00
I'm going to need to dig into this to see where the problem is happening. Thanks for the details, @NobbZ!

**Comment by kytrinyx** [comment] 2017-08-19 04:51
> As it seems there is no equivalent of the debug subcommand, nor is there a --verbose option for download. So I am not able to provide more details.

The CLI is still under active development. I will be doing what I can to add all of this in the next few days.

I am seeing the same behavior on my machine, and was able to identify the problem.

The payload from the API is:

```
{
	"solution": {
		"id": "2e08e167-0916-413d-b3d5-7d89941c9134",
		"url": "https://v2.exercism.io/my/solutions/2e08e167-0916-413d-b3d5-7d89941c9134",
		"user": {
			"handle": "kytrinyx",
			"is_requester": true
		},
		"exercise": {
			"id": "hello-world",
			"instructions_url": "https://v2.exercism.io/my/solutions/2e08e167-0916-413d-b3d5-7d89941c9134",
			"track": {
				"id": "erlang",
				"language": "Erlang"
			}
		},
		"file_download_base_url": "https://api.exercism.io/v1/solutions/2e08e167-0916-413d-b3d5-7d89941c9134/files/",
		"files": ["README.md", "include", "include/exercism.hrl", "rebar.config", "src", "src/hello_world.app.src", "src/hello_world.erl", "test", "test/hello_world_tests.erl"],
		"iteration": null
	}
}
```

When the CLI makes the call to the server to get the "include" file that is listed in the files list:

```
curl -XGET -v -H "Authorization: Bearer $TOKEN" "https://api.exercism.io/v1/solutions/2e08e167-0916-413d-b3d5-7d89941c9134/files/include"
```

it receives a `200 OK` with a `Content-Length: 0`

I believe we need to filter out directories from the `files` on the backend.

**Comment by kytrinyx** [comment] 2017-08-19 20:34
Just a quick note to say that we've got this reproduced and narrowed down. We'll post back when we've got a deploy fixed.

**Comment by amoradell** [comment] 2017-08-19 20:44
Same problem on Windows with tests subdirectory

d:\exercism>cli\nextercism download hello-world --track elm
2017/08/19 22:14:51 open d:\exercism\elm\hello-world\ tests \Tests.elm: The system cannot find the path specified.

tests directory wasn't created. instead it's a file.

d:\exercism>dir elm\hello-world /AH /AA
19/08/2017 22:23 206 .solution.json
19/08/2017 22:23 344 elm-package.json
19/08/2017 22:23 673 HelloWorld.elm
19/08/2017 22:23 337 package.json
19/08/2017 22:23 1 401 README.md
19/08/2017 22:23 0 tests

**Comment by ccare** [comment] 2017-08-22 10:14
This should be fixed now. `nextercism download hello-world --track=elm` now works for me. I would appreciate a sanity test from @NobbZ or @amoradell . Thanks for spotting this.

**Comment by NobbZ** [comment] 2017-08-22 10:23
I'll check later this day, when I'm back at my nextercism box.

**Comment by ccare** [comment] 2017-08-22 11:04
Thanks @NobbZ, much appreciated.

**Comment by NobbZ** [comment] 2017-08-22 14:12
Seems to work now, but I had to remove those empty file first:

```
$ nextercism download hello-world --track=erlang
2017/08/22 16:11:38 open /home/nobbz/nextercism/erlang/hello-world/include/exercism.hrl: not a directory
$ rm -rf $(nextercism w)/erlang/hello-world/include
$ nextercism download hello-world --track=erlang

Downloaded to
/home/nobbz/nextercism/erlang/hello-world
```

**Comment by kytrinyx** [comment] 2017-08-22 14:24
> but I had to remove those empty file first

I think that's acceptable in this case.

Thanks @ccare @NobbZ!

**Closed as completed by kytrinyx** 2017-08-22 14:24 UTC
Labels: type/bug, area/api

**Comment by NobbZ** [comment] 2017-08-22 15:11
>> but I had to remove those empty file first
>
> I think that's acceptable in this case.

I mentioned it, because I thought this could be a problem with the updating mechanism.

What if in language L tests are in file `test`, and after a year or so, we reorganize that track to have `test/*_test.L`?

**Comment by kytrinyx** [comment] 2017-08-22 17:11
I'm OK with that. I haven't seen a track that uses filenames without extensions, nor have I seen a track that uses directory names with dots in the name.

**Comment by amoradell** [comment] 2017-08-23 19:46
Thanks @ccare 
```
d:\exercism>cli\nextercism.exe download hello-world --track=elm
Downloaded to
d:\exercism\elm\hello-world

d:\exercism>tree elm
D:\EXERCISM\ELM
└───hello-world
    └───tests
```
