### ISSUE TITLE
mentorcism: It's returning 500 when I comment a solution

### ISSUE THREAD

**Issue by matheussilvasantos** [exercism/v2-feedback#208] opened 2018-07-12 02:42 UTC
![500](https://user-images.githubusercontent.com/14128874/42609647-f4d8f71c-8563-11e8-817d-231271ef171e.png)

**Comment by iHiD** [comment] 2018-07-12 12:29
Thank you for reporting :) Closing as duplicate of #173

**Closed as completed by iHiD** 2018-07-12 12:29 UTC
