### ISSUE TITLE
Tagline at bottom of site indicated 0 volunteers

### ISSUE THREAD

**Issue by Smarticles101** [exercism/v2-feedback#111] opened 2017-09-09 22:14 UTC
Ref. #5 

I laughed a little when I saw this for some reason.
<img width="457" alt="screen shot 2017-09-09 at 5 04 33 pm" src="https://user-images.githubusercontent.com/11557291/30244365-216bf1f8-9582-11e7-81ca-8b7579e0008f.png">

**Comment by rpottsoh** [comment] 2017-09-10 13:41
The issue resurfaced after the database from V1 was imported.  They are aware of this, it is on the list of issues to deal with.


Sent from my android device.

**Comment by iHiD** [comment] 2017-09-11 15:09
Triaged to https://github.com/exercism/reboot/issues/60

**Comment by rpottsoh** [comment] 2017-09-11 15:14
> exercism/reboot#60

Is `reboot` a private repo?  I get a 404 if I try to visit `#60`.

**Comment by iHiD** [comment] 2017-09-11 15:27
Yeah. It's private. It's where all the discussions about everything have been over the last 9 months, where we wanted just a core product team working on them (ie, Katrina and Thalamus team). We're now using it for tracking issues for website. We'll probably scrap it once we launch.

**Comment by iHiD** [comment] 2018-05-09 11:09
Duplicate of #90

**Closed as completed by iHiD** 2018-05-09 11:09 UTC
Labels: status/triaged
