### ISSUE TITLE
UI: Scrolling in a submission feels wonky

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-feedback#20] opened 2017-08-19 08:11 UTC
When look at a submission which is longer than my viewport height, then I do not see a scrollbar at first in the files, but when I scroll the page down to the bottom a scrollbar is enabled at the file view and the file view gets scrollable.

This leads on huge screens to a relatively small comment box pinned to the top of the browser, while commenting. Since I have to move my eye all the time from code at the bottom left to my comment on the top right I struggle to find the correct place when going back to the code.

Also it is irritating when I have my mouse over the code, use the scroll wheel and sometimes the hole page scrolls and sometimes the code. It just felt wonky and it took me a while to figure out what exactly is the wonky thing.

This has been discovered while I opened a to-be-mentored hello-world in go and looked at the testuite tab.

**Comment by kytrinyx** [comment] 2017-08-19 14:46
Thanks for reporting this @NobbZ.

**Comment by ilya-khadykin** [comment] 2017-08-22 10:54
One example of this:

<details>

![](http://g.recordit.co/VSWSGl5UKU.gif)

</details>

<br/>Reproducible on:
- Google Chrome
- Microsoft Edge

**Comment by budmc29** [comment] 2017-09-04 23:54
Can confirm the same issues on Chromium.

There are also some very weird behaviour when you have many files uploaded.
If you try to scroll to the end of the page, it will reset and you will be sent back, on Firefox it will freeze the page (older version).

https://v2.exercism.io/my/solutions/14fce8bf-a8a2-4efa-bdc4-04dc16590922 (Check iteration 1)

Sorry, but could not convince Nimbus to record the screen and I don't have any other screen capture software on my machine.

**Comment by iHiD** [comment] 2017-09-11 17:02
Triaged to exercism/reboot#139

**Comment by iHiD** [comment] 2018-05-19 15:04
I've re-worked quite a bit of this and it feels good to me now. I've fixed enough scrolling bugs that if there are still issues, I'd like to them to be individual issues. So I'm going to close this one for now but when we deploy the new beta (mid-June?), please do open any new scrolling issues you have. Thanks everyone!

**Closed as completed by iHiD** 2018-05-19 15:04 UTC
Labels: area/solution, status/fixed-on-master

**Comment by iHiD** [comment] 2018-05-19 15:13
For reference this is what it looks like now on my mac and what it should look like everywhere: http://recordit.co/5DNrBjbAzj
