### ISSUE TITLE
mentorcism: Comment button broken and doesn't provide visual feedback

### ISSUE THREAD

**Issue by melston** [exercism/v2-feedback#173] opened 2018-06-25 15:00 UTC
I was responding to a comment from a mentor but the comment button appeared to not be enabled.  I pressed the button a few times but got no visual feedback.  When I came back to the exercise later I noticed that I got several copies of my comment in the comment section.

**Comment by mgmatola** [comment] 2018-06-27 03:13
Here's an example of that:

https://mentors-beta.exercism.io/my/solutions/92605147430c4187aae40729a5a58b48

In my case, I figured out that that the comment button wasn't posting the comment (after pressing it *many* times) because the mentor had approved my solution. I still wanted to respond to the mentor's comment even after receiving approval and completing the assignment.

**Comment by melston** [comment] 2018-06-27 04:32
Apparently the page you refer to is private.  I can't see it.  You might be able to post a screenshot, or partial screenshot of it, though.

**Comment by mgmatola** [comment] 2018-06-27 14:52
https://docs.google.com/document/d/10Q2i4a4jk85-xf_HlcAYIAK5vXuWmGlgTMGXBFMsMdU/edit?usp=sharing

**Comment by iHiD** [comment] 2018-06-27 16:31
Also confirmed in #184. I've marked this as something that needs fixing. Thanks for reporting :)

**Comment by frerich** [comment] 2018-06-30 17:46
I just got bitten by this myself (and noticed that others mentoring my submissions apparently hit this issue, too).

**Comment by iHiD** [comment] 2018-07-01 12:41
There's two issues here.

1) The comment button is just a bit broken due to us not having redis configured correctly on the servers.
2) Buttons should be disabled once they're clicked.

I've triaged the second, and the first will be sorted when we deploy the proper stack. Thanks everyone.

**Comment by luisalima** [comment] 2018-07-05 07:49
Yup, just got this too! 👍 

Firefox Quantum 60.0.2 on a mac.

**Comment by kytrinyx** [comment] 2018-07-17 19:05
_This repo is being deprecated. We've imported this issue to the https://github.com/exercism/exercism.io repository._

**Closed as completed by kytrinyx** 2018-07-17 19:05 UTC
Labels: type/ui-tweak, status/triaged
