### ISSUE TITLE
Progress bar on Joined tracks section on My tracks page overlaps text

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v2-feedback#101] opened 2017-08-29 07:11 UTC
On the My tracks page, there is a section for tracks I've joined and tracks I haven't joined. Both try to display the number of exercises in the track, but that doesn't really work very well when you've completed a significant part of the track as the progress bar is rendered on top op the number of exercises:

![image](https://user-images.githubusercontent.com/135246/29808783-bff96fea-8c99-11e7-8945-33611edd8c22.png)

**Comment by NobbZ** [comment] 2017-08-29 07:39
Duplicate of #91

**Comment by ErikSchierboom** [comment] 2017-08-29 07:45
@NobbZ Sorry, missed that!

**Closed as completed** 2017-08-29 07:45 UTC
