### ISSUE TITLE
Error when viewing exercises when not signed in

### ISSUE THREAD

**Issue by wolf99** [exercism/v2-feedback#113] opened 2017-10-02 09:25 UTC
If not signed in and I visit a language, eg C++, then click to view all the exercises and then click one of the exercises, say the hello world (https://v2.exercism.io/tracks/cpp/exercises/hello-world) - the result is an "Oh dear, something's not working here...". Unsure if this is covered by #2 or not.

**Comment by emcoding** [comment] 2018-05-08 15:44
Can't reproduce, it seems to be solved.

**Comment by iHiD** [comment] 2018-05-09 11:10
I can't reproduce this either so closing :)

**Closed as completed by iHiD** 2018-05-09 11:10 UTC

**Comment by wolf99** [comment] 2018-05-23 11:26
Just to confirm: I can't see this anymore either.
FYI the exercise icons look great!
