### ISSUE TITLE
mentorcism: Don't preventing from send multiples requests

### ISSUE THREAD

**Issue by matheussilvasantos** [exercism/v2-feedback#207] opened 2018-07-12 02:38 UTC
The button should be disabled when I submit a comment. This way, it will not submit another request if I click twice.

![button](https://user-images.githubusercontent.com/14128874/42609518-60306ad2-8563-11e8-834c-a964c59560cf.png)

**Comment by iHiD** [comment] 2018-07-12 12:30
Thank you for reporting :) Closing as duplicate of #173

**Closed as completed by iHiD** 2018-07-12 12:30 UTC
